apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollout-bluegreen
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "bluegreen-test.k8s-26.sa"
spec:
  rules:
    - host: bluegreen-test.k8s-25.sa
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: rollout-bluegreen-active
                 port:
                   number: 8080
